apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      commands : ["/bin/echo"]
      args : ["hello","world"]
  
 #kubectl run nginx --image=nginx --command -- echo "hi" 