apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset        # Name of the DaemonSet
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx               # Must match the Pod template's labels
  template:
    metadata:
      labels:
        app: nginx             # Label applied to Pods created by this DaemonSet
    spec:
      containers:
        - name: nginx          # Container name
          image: nginx:latest  # Image to run
          ports:
            - containerPort: 80  # Expose port 80 inside the Pod



# Explanation:

# DaemonSet: ensures that one Pod runs on every node in the cluster.

# selector.matchLabels must match the labels in the Pod template; otherwise, Pods won’t be created.

# When a new node joins the cluster, the DaemonSet automatically schedules a Pod on it.

# Common real-world use cases:

  # Logging agents (e.g., Fluentd, Filebeat).

  # Monitoring agents (e.g., Prometheus Node Exporter).

  # Networking components (e.g., CNI plugins).